### ISSUE TITLE
Color gradient 

### ISSUE THREAD

**Issue by carrere** [cmdcolin/multibigwig#3]
Is there also any way to choose Colors for density display (instead of the red to blue gradient)?

**Comment by cmdcolin** [comment]
I think you can use pos_color and neg_color, as well as the bicolor_pivot value which is the value that is chosen to switch from "red to blue"

http://gmod.org/wiki/JBrowse_Configuration_Guide

I haven't tested that very much but I believe this works well for the MultiDensity track type

**Comment by cmdcolin** [comment]
It inherits from some of the default bigwig configs http://gmod.org/wiki/JBrowse_Configuration_Guide#Example_BigWig-based_Wiggle_Color_Density_Track_Configuration

**Comment by carrere** [comment]
Ok, I'll test tomorrow and send you feedback.
Thanks again for this really usefull plugin!

Seb

**Comment by carrere** [comment]
Thanks, it's working !

**Comment by cmdcolin** [comment]
Sweet :) Close for now
