### ISSUE TITLE
Fix label width

### ISSUE THREAD

**Issue by carrere** [cmdcolin/multibigwig#4]
Instead of adjust to label string

**Comment by cmdcolin** [comment]
Do you have a screenshot of how that looks? Curious about it

**Comment by carrere** [comment]
Here is an example:

![multibigwiglabels](https://cloud.githubusercontent.com/assets/1142779/15640928/55a45790-263d-11e6-9abb-84df390d050a.png)

**Comment by carrere** [comment]
Moreover, on this example, the first label is masked by the track title, but this is a Jbrowse side problem

**Comment by cmdcolin** [comment]
The label being masked by the track title is perpetually awkward but I added a new config item labelWidth that can configure a label width to be applied to all the subtracks.

**Comment by cmdcolin** [comment]
Lemme know if there is any feedback! Close for now

**Comment by carrere** [comment]
That works perfectly ! Thank you Colin !

**Comment by carrere** [comment]
You're right Keiran, this is what I do to bypass this issue.

**Comment by cmdcolin** [comment]
Glad that helps! If there was interest, I could have an option to render all the content lower than the tracklabel too, but otherwise I'll just keep it as is :)
